import 'package:flutter/material.dart';

class AppLocalizations {
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ar'),
  ];
}

// English translations
const Map<String, String> enTranslations = {
  'app_name': 'DentalFlow',
  'login': 'Login',
  'username': 'Username',
  'password': 'Password',
  'email': 'Email',
  'phone': 'Phone',
  'logout': 'Logout',
  'dashboard': 'Dashboard',
  'appointments': 'Appointments',
  'patients': 'Patients',
  'doctors': 'Doctors',
  'secretaries': 'Secretaries',
  'settings': 'Settings',
  'profile': 'Profile',
  'add': 'Add',
  'edit': 'Edit',
  'delete': 'Delete',
  'save': 'Save',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'search': 'Search',
  'filter': 'Filter',
  'export': 'Export',
  'print': 'Print',
  'close': 'Close',
  'back': 'Back',
  'next': 'Next',
  'previous': 'Previous',
  'loading': 'Loading...',
  'error': 'Error',
  'success': 'Success',
  'warning': 'Warning',
  'info': 'Information',
  'no_data': 'No data available',
  'try_again': 'Try Again',
  'forgot_password': 'Forgot Password?',
  'contact_admin': 'Contact Admin',
  'today': 'Today',
  'tomorrow': 'Tomorrow',
  'completed': 'Completed',
  'pending': 'Pending',
  'cancelled': 'Cancelled',
  'all': 'All',
  'status': 'Status',
  'time': 'Time',
  'date': 'Date',
  'duration': 'Duration',
  'reason': 'Reason',
  'notes': 'Notes',
  'full_name': 'Full Name',
  'age': 'Age',
  'gender': 'Gender',
  'blood_type': 'Blood Type',
  'allergies': 'Allergies',
  'medications': 'Current Medications',
  'medical_history': 'Medical History',
  'emergency_contact': 'Emergency Contact',
  'diagnosis': 'Diagnosis',
  'treatment': 'Treatment',
  'prescription': 'Prescription',
  'upload_xray': 'Upload X-Ray',
  'upload_photo': 'Upload Photo',
  'mark_completed': 'Mark as Completed',
  'schedule_followup': 'Schedule Follow-up',
};

// Arabic translations
const Map<String, String> arTranslations = {
  'app_name': 'دينتال فلو',
  'login': 'تسجيل الدخول',
  'username': 'اسم المستخدم',
  'password': 'كلمة المرور',
  'email': 'البريد الإلكتروني',
  'phone': 'الهاتف',
  'logout': 'تسجيل الخروج',
  'dashboard': 'لوحة التحكم',
  'appointments': 'المواعيد',
  'patients': 'المرضى',
  'doctors': 'الأطباء',
  'secretaries': 'السكرتيرات',
  'settings': 'الإعدادات',
  'profile': 'الملف الشخصي',
  'add': 'إضافة',
  'edit': 'تعديل',
  'delete': 'حذف',
  'save': 'حفظ',
  'cancel': 'إلغاء',
  'confirm': 'تأكيد',
  'search': 'بحث',
  'filter': 'تصفية',
  'export': 'تصدير',
  'print': 'طباعة',
  'close': 'إغلاق',
  'back': 'رجوع',
  'next': 'التالي',
  'previous': 'السابق',
  'loading': 'جاري التحميل...',
  'error': 'خطأ',
  'success': 'نجح',
  'warning': 'تحذير',
  'info': 'معلومة',
  'no_data': 'لا توجد بيانات',
  'try_again': 'حاول مجددًا',
  'forgot_password': 'هل نسيت كلمة المرور؟',
  'contact_admin': 'تواصل مع الإدارة',
  'today': 'اليوم',
  'tomorrow': 'غدا',
  'completed': 'مكتمل',
  'pending': 'قيد الانتظار',
  'cancelled': 'ملغي',
  'all': 'الكل',
  'status': 'الحالة',
  'time': 'الوقت',
  'date': 'التاريخ',
  'duration': 'المدة',
  'reason': 'السبب',
  'notes': 'ملاحظات',
  'full_name': 'الاسم الكامل',
  'age': 'العمر',
  'gender': 'النوع',
  'blood_type': 'فصيلة الدم',
  'allergies': 'الحساسيات',
  'medications': 'الأدوية الحالية',
  'medical_history': 'التاريخ الطبي',
  'emergency_contact': 'جهة الاتصال الطارئة',
  'diagnosis': 'التشخيص',
  'treatment': 'العلاج',
  'prescription': 'الوصفة الطبية',
  'upload_xray': 'تحميل أشعة X',
  'upload_photo': 'تحميل صورة',
  'mark_completed': 'وضع علامة على أنه مكتمل',
  'schedule_followup': 'جدولة متابعة',
};

String translate(String key, {bool isArabic = false}) {
  if (isArabic) {
    return arTranslations[key] ?? key;
  }
  return enTranslations[key] ?? key;
}
